language: python
python:
  - "2.7"

install:
  - python setup.py -q install
  - pip install -r test_requirements.txt  # pip incorrectly upgrades coverage 3.5 on first pass (pytest-cov requires >=3.4)
  - pip install -r test_requirements.txt  # install test_requirements again to downgrade it

services:
    - rabbitmq

script:
  - make test

notifications:
  email: false
  webhooks: http://finebot.herokuapp.com/hubot/travis/?room=30565_platform@conf.hipchat.com
