language: python
python:
  - "2.7"

install:
  - python setup.py -q install
  - pip install -r dev_requirements.txt
  # pip incorrectly upgrades coverage 3.5 on first pass
  # install dev_requirements again to downgrade it
  # see https://github.com/pypa/pip/issues/1249
  - pip install -r dev_requirements.txt

services:
    - rabbitmq

script:
  - make test
  - make docs

notifications:
  email: false
  webhooks:
    - http://finebot.herokuapp.com/hubot/travis/?room=30565_platform@conf.hipchat.com
    - http://readthedocs.org/build/nameko
	
