sudo: false
language: python
python:
  - "2.7"

services:
    - rabbitmq

addons:
  apt_packages:
    - libenchant-dev

install:
  - pip install tox

env:
    - TOX_ENV=py27-oldest
    - TOX_ENV=py27-pinned
    - TOX_ENV=py27-latest
    - TOX_ENV=py33-oldest
    - TOX_ENV=py33-pinned
    - TOX_ENV=py33-latest
    - TOX_ENV=py34-oldest
    - TOX_ENV=py34-pinned
    - TOX_ENV=py34-latest
    - TOX_ENV=docs
    - TOX_ENV=spelling

script:
  - tox -e $TOX_ENV

notifications:
  email: false
  irc:
    channels:
      - "chat.freenode.net#nameko"
    use_notice: true
    skip_join: true
  hipchat:
    rooms:
      secure: HdQuYHfBbCnuw0mgj1tJOdlXRhF+b9Ena6JVp1nPdCjP5WX8iCpDAtR4vlTry4X6eNXodb0xsdhWmN9Zq+iDvR0FQvvtRkFUxNpxsqGPLClvUIthTNqjGLgl2lMtbZcHRT1dj/wrKY/yAVdGs/FF/Ghz0MQZgiWtGA5hnb3kZAI=
    format: html
    template:
      - '%{repository}#%{build_number} (%{branch} - %{commit} : %{author}): %{message} (<a href="%{build_url}">Details</a>/<a href="%{compare_url}">Diff</a>)'

